### ISSUE TITLE
ItemDetail has only private members and no getters

### ISSUE THREAD

**Issue by DaPutzy** [xhsun/gw2wrapper#34]
The class `me.xhsun.guildwars2wrapper.model.v2.util.itemDetail.ItemDetail` has only private members and no getters, or am i missing sth?

![screen1](https://user-images.githubusercontent.com/9727551/33759687-89fb0c78-dc03-11e7-8e7b-df0af794f7ff.jpg)

**Comment by xhsun** [comment]
Ah yes... that class is meant to be like that. If you go to the wiki page for [items](https://wiki.guildwars2.com/wiki/API:2/items), you'll see depend on the type of that item, it will have different details. 

So what I did at that time was to create a general item detail class that contains all kind of details I might need. Depend on the item type, each specific item detail class will grant you access to correct details. Those classes can be find in ```me.xhsun.guildwars2wrapper.model.v2.util.itemDetail``` package.

Thus, what I suggest you may want to do is get the item type use ```getType()```, then cast what you get from ```getDetails()``` to the specific item detail class.

I'll probably add more javadoc for ```getDetails()```, so that it is less confusing. But if you have any better suggestion, please let me know!

**Comment by DaPutzy** [comment]
I assume you meant it like that:

    if (item.getType() == Item.Type.Weapon) {
        final Weapon weapon = (Weapon) item.getDetails();

        System.out.println(weapon);
    }

that however throws this:

    Exception in thread "main" java.lang.ClassCastException: me.xhsun.guildwars2wrapper.model.v2.util.itemDetail.ItemDetail cannot be cast to me.xhsun.guildwars2wrapper.model.v2.util.itemDetail.Weapon
	at Main.main(Main.java:18)

**Comment by xhsun** [comment]
Yep, that is what I meant. 

I fixed the issue that caused ```ClassCastException```, which means you can now downcast it without issue (hopefully).
